# Generated by Django 5.1.6 on 2025-03-16 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('groups', 'Groups'), ('themes', 'Themes'), ('work', 'Work'), ('soutenance', 'Soutenance')], help_text='Unique identifier for the timeline', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name of the timeline', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the timeline's purpose")),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this timeline becomes active')),
                ('end_date', models.DateTimeField(blank=True, help_text='When this timeline ends (leave blank for open-ended)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timeline is currently enabled')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'ordering': ['start_date', 'slug'],
            },
        ),
    ]
