# Generated by Django 5.1.6 on 2025-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='academic_program',
            field=models.CharField(choices=[('preparatory', 'Preparatory'), ('superior', 'Superior')], default='superior', help_text='Department/academic program for this timeline', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='academic_year',
            field=models.PositiveSmallIntegerField(default=2, help_text='Academic year applicable to this timeline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='specialty',
            field=models.CharField(choices=[('IASD', 'IASD'), ('SIW', 'SIW'), ('ISI', 'ISI'), ('1CS', '1CS'), ('2CPI', '2CPI')], default='common', help_text='Specialty for students in this timeline', max_length=20),
        ),
    ]
