# Generated by Django 5.1.6 on 2025-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timeline_academic_program_timeline_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('slug', 'academic_year', 'academic_program', 'specialty')},
        ),
    ]
