# Generated by Django 5.1.6 on 2025-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timeline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='slug',
            field=models.CharField(choices=[('groups', 'Groups'), ('themes', 'Themes'), ('work', 'Work'), ('soutenance', 'Soutenance')], help_text='Unique identifier for the timeline', max_length=20),
        ),
    ]
