# Generated by Django 5.1.6 on 2025-04-14 18:54

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('administrator', 'Administrator')], max_length=20)),
                ('profile_picture_url', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png', help_text="URL of the user's profile picture", max_length=500, null=True)),
                ('country', django_countries.fields.CountryField(default='DZ', max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a valid phone number with country code', max_length=128, null=True, region=None, unique=True)),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Year must be between 1900 and 2099', regex='^(19\\d{2}|20\\d{2})$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('enrollment_year', models.PositiveIntegerField(default=2014, help_text='Year of admission')),
                ('current_year', models.CharField(choices=[('2', '2nd Year'), ('3', '3rd Year'), ('4siw', '4th Year SIW'), ('4isi', '4th Year ISI'), ('4iasd', '4th Year IASD'), ('5siw', '5th Year SIW'), ('5isi', '5th Year ISI'), ('5iasd', '5th Year IASD')], help_text='Current year in the program', max_length=5)),
                ('academic_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(choices=[('professeur', 'Professeur'), ('maitre_conferences_a', 'Maître de conférences A'), ('maitre_conferences_b', 'Maître de conférences B'), ('maitre_assistant_a', 'Maître assistant A'), ('maitre_assistant_b', 'Maitre assistant B')], default='maitre_assistant_b', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Skill',
                'verbose_name_plural': 'Student Skills',
                'unique_together': {('student', 'name')},
            },
        ),
    ]
