# Generated by Django 5.1.6 on 2025-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current year in the program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(default=2014, help_text='Year of admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='ZAARIR', max_length=20, unique=True),
        ),
    ]
