# Generated by Django 5.1.6 on 2025-04-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.TextField(blank=True, help_text='A short description about the user', null=True),
        ),
    ]
