# Generated by Django 5.1.6 on 2025-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_current_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='ZAARIR', max_length=20),
        ),
    ]
