# Generated by Django 5.1.6 on 2025-03-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
