# Generated by Django 5.1.6 on 2025-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.CharField(choices=[('professeur', 'Professeur'), ('maitre_conferences_a', 'Maître de conférences A'), ('maitre_conferences_b', 'Maître de conférences B'), ('maitre_assistant_a', 'Maître assistant A'), ('maitre_assistant_b', 'Maitre assistant B')], default='maitre_assistant_b', max_length=50),
        ),
    ]
