version: '3.8'

services:
  backend:
    image: "zaarirmoh/pfe:test"
    container_name: pfe_backend
    depends_on:
      - redis
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: "redis:7-alpine"
    container_name: pfe_redis
    restart: always
    ports:
      - "6379:6379"

