# Generated by Django 5.1.6 on 2025-03-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('title', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('IASD', 'IASD'), ('SIW', 'SIW'), ('ISI', 'ISI'), ('1CS', '1CS'), ('2CPI', '2CPI')], max_length=100)),
                ('description', models.TextField()),
                ('tools', models.TextField(help_text='Enter tools')),
                ('academic_year', models.PositiveSmallIntegerField(help_text='Must match the academic year of the linked Timeline')),
                ('academic_program', models.CharField(choices=[('preparatory', 'Preparatory'), ('superior', 'Superior')], help_text='Must match the academic program of the linked Timeline', max_length=20)),
                ('co_supervisors', models.ManyToManyField(blank=True, related_name='co_supervised_themes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('documents', models.ManyToManyField(blank=True, related_name='themes', to='documents.document')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_themes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
