# Generated by Django 5.1.6 on 2025-04-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='themeassignment',
            name='unique_theme_assignment',
        ),
        migrations.AlterField(
            model_name='themeassignment',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teams', to='themes.theme'),
        ),
    ]
