# Generated by Django 5.1.6 on 2025-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='timeline',
        ),
        migrations.AlterField(
            model_name='theme',
            name='tools',
            field=models.TextField(help_text='Enter tools'),
        ),
    ]
