# Generated by Django 5.1.6 on 2025-04-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the theme has been verified by the administration.'),
        ),
    ]
