# Generated by Django 5.1.6 on 2025-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the theme has been verified by the administration.'),
        ),
        migrations.AddField(
            model_name='themeassignment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
