# Generated by Django 5.1.6 on 2025-05-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeassignment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
