# Generated by Django 5.1.6 on 2025-04-23 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_remove_themeassignment_unique_theme_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesupervisionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_supervision_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
