# Generated by Django 5.1.6 on 2025-03-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_remove_theme_timeline_alter_theme_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='co_supervisors',
            field=models.ManyToManyField(blank=True, related_name='co_supervised_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
