# Generated by Django 5.1.6 on 2025-05-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('title', models.CharField(blank=True, help_text='Short title for the notification', max_length=255)),
                ('content', models.TextField(help_text='Main notification message content')),
                ('type', models.CharField(choices=[('team_invitation', 'Team Invitation'), ('team_update', 'Team Update'), ('team_membership', 'Team Membership'), ('project_update', 'Project Update'), ('deadline', 'Deadline Reminder'), ('status', 'Status Update'), ('activity', 'Activity Notification'), ('system', 'System Notification')], help_text='Type of notification', max_length=20)),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('archived', 'Archived')], default='unread', help_text='Current status of the notification', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the notification', max_length=10)),
                ('action_url', models.CharField(blank=True, help_text='URL for the action button in the notification', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for notification rendering and behavior')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
