# Generated by Django 5.1.6 on 2025-03-12 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for notification rendering and behavior'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='Short title for the notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL for the action button in the notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(help_text='Main notification message content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the notification', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('archived', 'Archived')], default='unread', help_text='Current status of the notification', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('team_invitation', 'Team Invitation'), ('team_update', 'Team Update'), ('team_membership', 'Team Membership'), ('project_update', 'Project Update'), ('deadline', 'Deadline Reminder'), ('status', 'Status Update'), ('activity', 'Activity Notification'), ('system', 'System Notification')], help_text='Type of notification', max_length=20),
        ),
    ]
