# Generated by Django 5.1.6 on 2025-03-21 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Unique identifier for the timeline', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name of the timeline', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the timeline's purpose")),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this timeline becomes active')),
                ('end_date', models.DateTimeField(blank=True, help_text='When this timeline ends (leave blank for open-ended)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timeline is currently enabled')),
                ('timeline_type', models.CharField(choices=[('groups', 'Groups'), ('themes', 'Themes'), ('work', 'Work'), ('soutenance', 'Soutenance')], help_text='Type of timeline', max_length=20)),
                ('academic_program', models.CharField(choices=[('preparatory', 'Preparatory'), ('superior', 'Superior')], help_text='Academic program this timeline applies to', max_length=20)),
                ('academic_year', models.PositiveSmallIntegerField(help_text='Academic year this timeline applies to (1, 2, or 3)')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'ordering': ['academic_program', 'academic_year', 'start_date', 'timeline_type'],
                'unique_together': {('timeline_type', 'academic_program', 'academic_year')},
            },
        ),
    ]
