# Generated by Django 5.1.6 on 2025-05-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jury Role',
                'verbose_name_plural': 'Jury Roles',
            },
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Room')),
                ('defense_uri', models.URLField(blank=True, verbose_name='Defense URI')),
                ('report_uri', models.URLField(blank=True, verbose_name='Report URI')),
                ('specifications_document_uri', models.URLField(blank=True, verbose_name='Specifications Document URI')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20, verbose_name='Status')),
                ('result', models.TextField(blank=True, verbose_name='Result')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Grade')),
                ('theme_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='themes.themeassignment', verbose_name='Theme Assignment')),
            ],
            options={
                'verbose_name': 'Defense',
                'verbose_name_plural': 'Defenses',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_president', models.BooleanField(default=False, verbose_name='Is President')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='supervision.defense', verbose_name='Defense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_members', to='supervision.juryrole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Jury Member',
                'verbose_name_plural': 'Jury Members',
            },
        ),
        migrations.AddField(
            model_name='defense',
            name='jury',
            field=models.ManyToManyField(related_name='jury_in_defenses', through='supervision.JuryMember', to=settings.AUTH_USER_MODEL, verbose_name='Jury'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=20)),
                ('location_details', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='teams.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='teams.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
