# Generated by Django 5.1.6 on 2025-05-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='defense_uri',
            field=models.URLField(blank=True, verbose_name='Defense URI'),
        ),
        migrations.AddField(
            model_name='defense',
            name='report_uri',
            field=models.URLField(blank=True, verbose_name='Report URI'),
        ),
        migrations.AddField(
            model_name='defense',
            name='specifications_document_uri',
            field=models.URLField(blank=True, verbose_name='Specifications Document URI'),
        ),
    ]
