# Generated by Django 5.1.6 on 2025-05-22 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervision', '0001_initial'),
        ('teams', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='theme_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='themes.themeassignment', verbose_name='Theme Assignment'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='defense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='supervision.defense', verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='defense',
            name='jury',
            field=models.ManyToManyField(related_name='jury_in_defenses', through='supervision.JuryMember', to=settings.AUTH_USER_MODEL, verbose_name='Jury'),
        ),
        migrations.AddField(
            model_name='jurymember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_members', to='supervision.juryrole', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='teams.team'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='teams.team'),
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='supervision.upload'),
        ),
    ]
