# Generated by Django 5.1.6 on 2025-03-14 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamjoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teamjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'requester'), name='unique_pending_request'),
        ),
    ]
