# Generated by Django 5.1.6 on 2025-03-14 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teamjoinrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamjoinrequest',
            name='unique_pending_request',
        ),
        migrations.AddField(
            model_name='team',
            name='maximum_members',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together={('team', 'requester', 'status')},
        ),
    ]
