# Generated by Django 5.1.6 on 2025-03-16 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_teamjoinrequest_unique_pending_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the inviter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='maximum_members',
            field=models.PositiveSmallIntegerField(help_text='Maximum number of members allowed in this team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('maximum_members', models.PositiveSmallIntegerField(default=6, help_text='Maximum number of students allowed in a single team', validators=[django.core.validators.MinValueValidator(2, message='Teams must allow at least 2 members'), django.core.validators.MaxValueValidator(20, message='Teams cannot exceed 20 members')])),
                ('allow_cross_program_teams', models.BooleanField(default=False, help_text='If enabled, students from different programs can join the same team')),
                ('allow_cross_year_teams', models.BooleanField(default=False, help_text='If enabled, students from different academic years can join the same team')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Team Settings',
                'verbose_name_plural': 'Team Settings',
            },
        ),
    ]
