# Generated by Django 5.1.6 on 2025-03-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teaminvitation_message_alter_team_maximum_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
